spring.profiles.active=local
spring.application.name=spring-profile-service

logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.com.erebelo.springprofileservice=INFO

server.servlet.contextPath=/spring-profile-service

# Actuator endpoint
management.endpoints.access.default=none
management.endpoint.health.access=read_only

# MongoDB connection settings
spring.mongodb.uri=mongodb://localhost:27017/profile_db?replicaSet=rs0